### ISSUE TITLE
Print new robot monkey

### ISSUE THREAD

**Issue by bnolan** [camp8bit/forest-lighting#14]
Less 🍆 ! Has screws! Has switch!

https://github.com/camp8bit/forest-lighting/blob/master/openscad/robot-monkey-face.scad

![screen shot 2016-10-14 at 5 52 48 pm](https://cloud.githubusercontent.com/assets/17499/19376183/fa86a7a2-9237-11e6-9e83-3938f66991ad.png)

**Comment by stojg** [comment]
starting a print for https://github.com/camp8bit/forest-lighting/blob/master/stl/robot-monkey-face.stl (also committed wanhao gcode file)

**Comment by bnolan** [comment]
Done. Printed out 4 of them - plus stig did 1, looking good. I'll print out two per day for the next week or so.
