### ISSUE TITLE
Print trial enclosure

### ISSUE THREAD

**Issue by bnolan** [camp8bit/forest-lighting#2]
Print enclosure for PIR sensor + arduino:

https://github.com/camp8bit/forest-lighting/blob/master/openscad/PIRHolder.scad

<img width="478" alt="screen shot 2016-10-03 at 4 29 19 pm" src="https://cloud.githubusercontent.com/assets/17499/19026828/fa2ccc50-8986-11e6-9bc6-2d385ce2b108.png">

It would be good to print it to be waterproof for the production run, but for these initial test-fit ones don't need to go crazy with number of shells.

**Comment by stojg** [comment]
![img_1317](https://cloud.githubusercontent.com/assets/485130/19029023/e9cd205e-899e-11e6-8da6-81e8945292fb.png)
![img_1316](https://cloud.githubusercontent.com/assets/485130/19029022/e9ccdc84-899e-11e6-8ac0-f58ac3b95d24.png)
