### ISSUE TITLE
Print rounded robot face

### ISSUE THREAD

**Issue by bnolan** [camp8bit/forest-lighting#3]
Trial print of rounded robot face (enclosure for lighting).

https://github.com/camp8bit/forest-lighting/blob/master/openscad/rounded-robot-face.scad

<img width="480" alt="screen shot 2016-10-08 at 2 16 42 pm" src="https://cloud.githubusercontent.com/assets/17499/19209206/21ca1568-8d62-11e6-807e-f397a99e0746.png">

**Comment by bnolan** [comment]
Added mounting points.

<img width="640" alt="screen shot 2016-10-08 at 2 29 57 pm" src="https://cloud.githubusercontent.com/assets/17499/19209292/cccb4b84-8d63-11e6-91da-689ed8959ab1.png">

**Comment by bnolan** [comment]
Okay, another last minute thing - 56038de has a larger occipital area so that the board can fit inside the stepped area.
<img width="663" alt="screen shot 2016-10-08 at 2 35 25 pm" src="https://cloud.githubusercontent.com/assets/17499/19209315/771efaea-8d64-11e6-9324-32d0f6b71c77.png">

**Comment by stojg** [comment]
![image](https://cloud.githubusercontent.com/assets/485130/19210789/617b362a-8d89-11e6-8159-6dca6546c956.png)

1) PIR hole is a bit to small compared to the previous print
2) "it could (if you have a less dirty mind I guess) be a weird monkey"
3) It's hard to open once properly closed, maybe a little cut out on the bottom where a screwdriver or a nail can be used as a leverage to open it.
